export const data = JSON.parse("{\"key\":\"v-40da31cf\",\"path\":\"/%E6%96%87%E7%AB%A0/%E5%88%86%E7%B1%BB/js/this_problem/%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0.html\",\"title\":\"箭头函数中的this指向\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"edit\",\"date\":\"2023-07-02T00:00:00.000Z\",\"category\":[\"js\"],\"tag\":[\"this指向问题\",\"面试题\"],\"star\":true,\"sticky\":true,\"copy.disableCopy\":true,\"description\":\"箭头函数中的this指向 在箭头函数中,this指向,父级程序的this指向 如果父级程序有this指向,那么箭头函数指向的就是父级程序的this 如果父级程序没有this指向,那么指向的就是window\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://wei-z.top/%E6%96%87%E7%AB%A0/%E5%88%86%E7%B1%BB/js/this_problem/%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Aurora's Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"箭头函数中的this指向\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"箭头函数中的this指向 在箭头函数中,this指向,父级程序的this指向 如果父级程序有this指向,那么箭头函数指向的就是父级程序的this 如果父级程序没有this指向,那么指向的就是window\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aurora\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"this指向问题\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"面试题\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-07-02T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"箭头函数中的this指向\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-07-02T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aurora\\\",\\\"url\\\":\\\"https://gitee.com/agaion1110\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"箭头函数\",\"slug\":\"箭头函数\",\"link\":\"#箭头函数\",\"children\":[]},{\"level\":2,\"title\":\"箭头函数的this指向\",\"slug\":\"箭头函数的this指向\",\"link\":\"#箭头函数的this指向\",\"children\":[{\"level\":3,\"title\":\"普通函数的this指向\",\"slug\":\"普通函数的this指向\",\"link\":\"#普通函数的this指向\",\"children\":[]},{\"level\":3,\"title\":\"箭头函数this指向\",\"slug\":\"箭头函数this指向\",\"link\":\"#箭头函数this指向\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.65,\"words\":794},\"filePathRelative\":\"文章/分类/js/this_problem/箭头函数.md\",\"localizedDate\":\"2023年7月2日\",\"excerpt\":\"<h1> 箭头函数中的this指向</h1>\\n<blockquote>\\n<ol>\\n<li>在箭头函数中,this指向,父级程序的this指向</li>\\n<li>如果父级程序有this指向,那么箭头函数指向的就是父级程序的this</li>\\n<li>如果父级程序没有this指向,那么指向的就是window</li>\\n</ol>\\n</blockquote>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
