export const data = JSON.parse("{\"key\":\"v-329d215c\",\"path\":\"/%E6%96%87%E7%AB%A0/%E5%88%86%E7%B1%BB/Vue/%E7%BB%84%E4%BB%B6%E9%97%B4%E6%B6%88%E6%81%AF%E7%9A%84%E4%BC%A0%E9%80%92/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6.html\",\"title\":\"自定义事件\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"edit\",\"date\":\"2023-07-26T00:00:00.000Z\",\"category\":[\"vue\"],\"tag\":[\"笔记\",\"面试题\"],\"star\":false,\"sticky\":false,\"copy.disableCopy\":true,\"description\":\"自定义事件 组件的自定义事件实现子组件向父组件传递数据的功能，所以，自定义事件的绑定需要在父组件中完成。 组件的自定义事件的触发需要在子组件中完成，给谁绑定的事件，就找谁触发。 在了解组件的自定义事件之前，我们也了解过props，props也能实现子组件向父组件通信，接下来展示的将是通过自定义事件完成子传父功能。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://wei-z.top/%E6%96%87%E7%AB%A0/%E5%88%86%E7%B1%BB/Vue/%E7%BB%84%E4%BB%B6%E9%97%B4%E6%B6%88%E6%81%AF%E7%9A%84%E4%BC%A0%E9%80%92/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Aurora's Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"自定义事件\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"自定义事件 组件的自定义事件实现子组件向父组件传递数据的功能，所以，自定义事件的绑定需要在父组件中完成。 组件的自定义事件的触发需要在子组件中完成，给谁绑定的事件，就找谁触发。 在了解组件的自定义事件之前，我们也了解过props，props也能实现子组件向父组件通信，接下来展示的将是通过自定义事件完成子传父功能。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aurora\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"笔记\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"面试题\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-07-26T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"自定义事件\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-07-26T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aurora\\\",\\\"url\\\":\\\"https://gitee.com/agaion1110\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"父组件：\",\"slug\":\"父组件\",\"link\":\"#父组件\",\"children\":[]},{\"level\":2,\"title\":\"子组件\",\"slug\":\"子组件\",\"link\":\"#子组件\",\"children\":[]},{\"level\":2,\"title\":\"Vue2和Vue3中的区别\",\"slug\":\"vue2和vue3中的区别\",\"link\":\"#vue2和vue3中的区别\",\"children\":[]}],\"readingTime\":{\"minutes\":2.4,\"words\":721},\"filePathRelative\":\"文章/分类/Vue/组件间消息的传递/自定义事件.md\",\"localizedDate\":\"2023年7月26日\",\"excerpt\":\"<h1> 自定义事件</h1>\\n<p>组件的自定义事件实现子组件向父组件传递数据的功能，所以，自定义事件的<strong>绑定</strong>需要在父组件中完成。</p>\\n<p>组件的自定义事件的<strong>触发</strong>需要在子组件中完成，给谁绑定的事件，就找谁触发。</p>\\n<p>在了解组件的自定义事件之前，我们也了解过<code>props</code>，<code>props</code>也能实现子组件向父组件通信，接下来展示的将是通过自定义事件完成子传父功能。</p>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
