export const data = JSON.parse("{\"key\":\"v-5dd645e4\",\"path\":\"/index/posts/js/this_problem/%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0.html\",\"title\":\"箭头函数中的this指向\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"edit\",\"category\":[\"js\"],\"tag\":[\"红\",\"圆\",\"小\"],\"star\":true,\"sticky\":true,\"description\":\"箭头函数中的this指向 在箭头函数中,this指向,父级程序的this指向 如果父级程序有this指向,那么箭头函数指向的就是父级程序的this 如果父级程序没有this指向,那么指向的就是window 箭头函数 ​ function(){} --- ()=&gt;{} 箭头函数 ​ function(e){} --- e =&gt;{} 箭头函数 ​ function(){一行} --- ()=&gt;一行 箭头函数 ​ function(e){一行} --- e =&gt;一行 箭头函数\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/index/posts/js/this_problem/%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Aurora's Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"箭头函数中的this指向\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"箭头函数中的this指向 在箭头函数中,this指向,父级程序的this指向 如果父级程序有this指向,那么箭头函数指向的就是父级程序的this 如果父级程序没有this指向,那么指向的就是window 箭头函数 ​ function(){} --- ()=&gt;{} 箭头函数 ​ function(e){} --- e =&gt;{} 箭头函数 ​ function(){一行} --- ()=&gt;一行 箭头函数 ​ function(e){一行} --- e =&gt;一行 箭头函数\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aurora\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"红\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"圆\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"小\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"箭头函数中的this指向\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aurora\\\",\\\"url\\\":\\\"https://mrhope.site\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"箭头函数\",\"slug\":\"箭头函数\",\"link\":\"#箭头函数\",\"children\":[]},{\"level\":2,\"title\":\"箭头函数的this指向\",\"slug\":\"箭头函数的this指向\",\"link\":\"#箭头函数的this指向\",\"children\":[{\"level\":3,\"title\":\"普通函数的this指向\",\"slug\":\"普通函数的this指向\",\"link\":\"#普通函数的this指向\",\"children\":[]},{\"level\":3,\"title\":\"箭头函数this指向\",\"slug\":\"箭头函数this指向\",\"link\":\"#箭头函数this指向\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.62,\"words\":786},\"filePathRelative\":\"index/posts/js/this_problem/箭头函数.md\",\"excerpt\":\"<h1> 箭头函数中的this指向</h1>\\n<blockquote>\\n<ol>\\n<li>在箭头函数中,this指向,父级程序的this指向</li>\\n<li>如果父级程序有this指向,那么箭头函数指向的就是父级程序的this</li>\\n<li>如果父级程序没有this指向,那么指向的就是window</li>\\n</ol>\\n</blockquote>\\n<h2> 箭头函数</h2>\\n<p>​    function(){}        ---   ()=&gt;{}     箭头函数\\n​    function(e){}       ---   e =&gt;{}     箭头函数\\n​    function(){一行}    ---   ()=&gt;一行    箭头函数\\n​    function(e){一行}   ---   e =&gt;一行    箭头函数</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
